"""Migrate to many-to-many relationship

Revision ID: 03865bb3abd0
Revises: a1b2c3d4e5f6
Create Date: 2026-02-02 16:32:06.835657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03865bb3abd0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_index(op.f('ix_book_authors_author_id'), 'book_authors', ['author_id'], unique=False)
    op.drop_index('ix_book_categories_book_id', table_name='book_categories')
    op.drop_index('ix_book_categories_category_id', table_name='book_categories')
    op.drop_index('ix_books_author_id', table_name='books')
    op.drop_constraint('fk_books_author_id', 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'author')
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_unique_constraint('categories_name_key', 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('books', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_books_author_id', 'books', 'authors', ['author_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_books_author_id', 'books', ['author_id'], unique=False)
    op.create_index('ix_book_categories_category_id', 'book_categories', ['category_id'], unique=False)
    op.create_index('ix_book_categories_book_id', 'book_categories', ['book_id'], unique=False)
    op.drop_index(op.f('ix_book_authors_author_id'), table_name='book_authors')
    op.drop_table('book_authors')
    # ### end Alembic commands ###
