"""Initial migration

Revision ID: af9bc3fd25e5
Revises: 
Create Date: 2025-12-10 16:45:10.073837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9bc3fd25e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=17),
               comment=None,
               existing_comment='ISBN-10 or ISBN-13 (normalized, no dashes/spaces)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=17),
               comment='ISBN-10 or ISBN-13 (normalized, no dashes/spaces)',
               existing_nullable=False)
    # ### end Alembic commands ###
